"""migration message

Revision ID: 0b1a2c846de8
Revises: cc7d81c26b12
Create Date: 2024-12-11 10:59:59

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import text as sa_text

# revision identifiers, used by Alembic.
revision: str = "0b1a2c846de8"
down_revision: Union[str, None] = "cc7d81c26b12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def common_columns():
    """Return common columns used in multiple tables."""
    return [
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "uuid",
            UUID(as_uuid=True),
            server_default=sa_text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa_text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa_text("CURRENT_TIMESTAMP"),
            onupdate=sa_text("CURRENT_TIMESTAMP"),
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
    ]


def upgrade() -> None:
    # ### end Alembic commands ###

    op.add_column("document_user_mapping", sa.Column("last_used", sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message_document_mapping", "last_used")
    # ### end Alembic commands ###
