"""update user model

Revision ID: 4bc86a1519fb
Revises: 9da7319b4073
Create Date: 2025-02-04 22:54:24.314844

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bc86a1519fb"
down_revision: Union[str, None] = "9da7319b4073"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("job_title", sa.String(length=255), nullable=True))
    op.add_column("user", sa.Column("region", sa.String(length=255), nullable=True))
    op.add_column("user", sa.Column("sector", sa.String(length=255), nullable=True))
    op.add_column("user", sa.Column("organisation", sa.String(length=255), nullable=True))
    op.add_column("user", sa.Column("grade", sa.String(length=255), nullable=True))
    op.add_column("user", sa.Column("communicator_role", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "communicator_role")
    op.drop_column("user", "grade")
    op.drop_column("user", "organisation")
    op.drop_column("user", "sector")
    op.drop_column("user", "region")
    op.drop_column("user", "job_title")
    # ### end Alembic commands ###
