"""add_theme_use_case_data

Revision ID: 711bc1565eb4
Revises: de6baed14170
Create Date: 2025-03-19 10:29:37.645034

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy import MetaData

# revision identifiers, used by Alembic.
revision: str = "711bc1565eb4"
down_revision: str | None = "de6baed14170"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    meta = MetaData()
    meta.reflect(bind=conn)
    op.execute(
        r"UPDATE use_case SET instruction = REPLACE(instruction, '\/', '/') "
        " WHERE title = 'I want to draft a toolkit for a campaign'"
        " and deleted_at is null"
    )

    op.execute(
        "UPDATE use_case SET title = 'I want to create some engaging headlines/event titles/articles'"
        r" ,instruction= REPLACE(instruction, '\/', '/')"
        r"  WHERE title = 'I want to create some engaging headlines\/event titles\/articles'"
        " and deleted_at is null"
    )

    op.execute(
        "UPDATE use_case SET "
        r" instruction= REPLACE(instruction, '\/', '/')"
        "  WHERE title = 'I want to explore a problem from different points of view'"
        " and deleted_at is null"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    meta = MetaData()
    meta.reflect(bind=conn)
    op.execute(
        "UPDATE use_case SET instruction = 'The goal is to create a document with instructions for"
        " stakeholders on how to use campaign"
        " assets and messaging as part of OASIS campaign. 1) Analyse the OASIS plan and campaign "
        "narrative. Identify the campaign objectives, target audiences and key campaign milestones "
        "from the OASIS plan. 2) Create instructions on how to use messaging and campaign assets to"
        " reach the target audience. These instructions should include recommended channels,"
        r" messaging and dates\/times to put out communications content. 3) Check that the "
        "instructions take into account the stakeholders characteristics.'"
        " WHERE title = 'I want to draft a toolkit for a campaign'"
        " and deleted_at is null"
    )

    op.execute(
        r"UPDATE use_case SET title = 'I want to create some engaging headlines\/event titles\/articles'"
        " ,instruction= 'Aim: Brainstorm Headlines\\/Titles.\nUsing the information provided, create 8-10 potential"
        " headlines or titles.\nEnsure they are concise, engaging, and relevant to the topic and"
        " audience.\nConsider using action verbs, thought-provoking questions, or relevant puns\\"
        "/phrases.\n\nFinal Recommendation:\nSuggest the 2-3 most compelling headline\\/titles that"
        " effectively represents the content and resonates with the target audience.\n\nGuidance for"
        " Use:\nStrive for clarity and impact while remaining true to the content's essence.\n"
        "Keep the language accessible and avoid technical jargon unless it's audience-appropriate."
        "\nTest the effectiveness of the headline\\/title by considering its appeal and clarity. '"
        "  WHERE title = 'I want to create some engaging headlines/event titles/articles'"
        " and deleted_at is null"
    )

    op.execute(
        "UPDATE use_case SET "
        " instruction= 'I want to think about this problem from several different perspectives."
        " Give perspectives from 8 different disciplines. Include the following disciplines:"
        " Economist, Service Designer, Behavioural Scientist, Social Researcher,"
        r" Innovator\/Entrepreneur. Choose the other disciplines yourself, depending on the problem."
        " Include their view on the problem, questions to explore, and potential solutions.'"
        "  WHERE title = 'I want to explore a problem from different points of view'"
        " and deleted_at is null"
    )

    # ### end Alembic commands ###
