"""Add position fields to Theme and UseCase

Revision ID: 8ea05d0d078e
Revises: 8ca7db7bfc4c
Create Date: 2024-10-16 14:30:47.472237

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ea05d0d078e"
down_revision: Union[str, None] = "8ca7db7bfc4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("theme", sa.Column("position", sa.Integer(), nullable=True))
    op.add_column("use_case", sa.Column("position", sa.Integer(), nullable=True))

    # Seed the position fields with the same value as the ID column
    op.execute("UPDATE theme SET position = id")
    op.execute("UPDATE use_case SET position = id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("theme", "position")
    op.drop_column("use_case", "position")
    # ### end Alembic commands ###
