"""Add use_gov_uk_search_api, enable_web_browsing properties

Revision ID: a4abacd8cee5
Revises: e357a42a4565
Create Date: 2025-01-27 12:15:16.305017

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4abacd8cee5"
down_revision: Union[str, None] = "d6a210c93e03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("chat", sa.Column("use_gov_uk_search_api", sa.Boolean(), server_default="false", nullable=True))
    op.add_column("chat", sa.Column("enable_web_browsing", sa.Boolean(), server_default="false", nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("chat", "use_gov_uk_search_api")
    op.drop_column("chat", "enable_web_browsing")

    # ### end Alembic commands ###
