"""Add extra user columns to auth session table

Revision ID: b968baf5196c
Revises: 4bc86a1519fb
Create Date: 2025-02-11 22:58:05.865277

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b968baf5196c"
down_revision: Union[str, None] = "4bc86a1519fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_session", sa.Column("job_title", sa.String(length=255), nullable=True))
    op.add_column("auth_session", sa.Column("region", sa.String(length=255), nullable=True))
    op.add_column("auth_session", sa.Column("sector", sa.String(length=255), nullable=True))
    op.add_column("auth_session", sa.Column("organisation", sa.String(length=255), nullable=True))
    op.add_column("auth_session", sa.Column("grade", sa.String(length=255), nullable=True))
    op.add_column("auth_session", sa.Column("communicator_role", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_session", "communicator_role")
    op.drop_column("auth_session", "grade")
    op.drop_column("auth_session", "organisation")
    op.drop_column("auth_session", "sector")
    op.drop_column("auth_session", "region")
    op.drop_column("auth_session", "job_title")
    # ### end Alembic commands ###
