"""migration message

Revision ID: cc7d81c26b12
Revises: 7a64c89486d2
Create Date: 2024-11-12 09:59:59.427533

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import text as sa_text

# revision identifiers, used by Alembic.
revision: str = "cc7d81c26b12"
down_revision: Union[str, None] = "7a64c89486d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def common_columns():
    """Return common columns used in multiple tables."""
    return [
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "uuid",
            UUID(as_uuid=True),
            server_default=sa_text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa_text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa_text("CURRENT_TIMESTAMP"),
            onupdate=sa_text("CURRENT_TIMESTAMP"),
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
    ]


def upgrade() -> None:
    op.create_index("idx_document_uuid_unique", "document", ["uuid"], unique=True)

    op.create_table(
        "chat_document_mapping",
        *common_columns(),
        sa.Column("document_uuid", sa.UUID(), sa.ForeignKey("document.uuid"), nullable=False),
        sa.Column("chat_id", sa.Integer(), sa.ForeignKey("chat.id"), nullable=False),
    )
    op.create_index("dx_chat_document_mapping_chat_id", "chat_document_mapping", ["chat_id"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_document_uuid_unique")
    op.drop_table("chat_document_mapping")
    # ### end Alembic commands ###
