"""Add tables for Gov UK Search integration

Revision ID: d6a210c93e03
Revises: 4bc86a1519fb
Create Date: 2025-02-19 14:59:02.417949

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6a210c93e03"
down_revision: Union[str, None] = "ce307e1fb75e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gov_uk_search_query",
        sa.Column("llm_internal_response_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["llm_internal_response_id"], ["llm_internal_response.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gov_uk_search_result",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("gov_uk_search_query_id", sa.Integer(), nullable=False),
        sa.Column("llm_internal_response_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["gov_uk_search_query_id"], ["gov_uk_search_query.id"]),
        sa.ForeignKeyConstraint(["llm_internal_response_id"], ["llm_internal_response.id"]),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("llm_internal_response", "system_prompt_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("llm_internal_response", "system_prompt_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_table("gov_uk_search_result")
    op.drop_table("gov_uk_search_query")
    # ### end Alembic commands ###
