"""add_description_to_user_prompt

Revision ID: e357a42a4565
Revises: 0al6cf1e171f
Create Date: 2025-01-06 13:58:40.272120

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e357a42a4565"
down_revision: Union[str, None] = "0al6cf1e171f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_prompt", sa.Column("description", sa.VARCHAR, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_prompt", "description")
    # ### end Alembic commands ###
