"""add llm models

Revision ID: e9824826ab24
Revises: ef9623b5ea8d
Create Date: 2024-05-28 11:11:11.211123

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import MetaData, Table

# revision identifiers, used by Alembic.
revision: str = "e9824826ab24"
down_revision: Union[str, None] = "ef9623b5ea8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

models = [
    {
        "model": "gpt-4o-2024-05-13",
        "provider": "openai",
    },
    {"model": "gpt-4-turbo-2024-05-09", "provider": "openai"},
    {
        "model": "gpt-4o",
        "provider": "openai",
    },
    {
        "model": "gpt-4-turbo",
        "provider": "openai",
    },
    {
        "model": "gpt-4-turbo-preview",
        "provider": "openai",
    },
    {
        "model": "gpt-4-0125-preview",
        "provider": "openai",
    },
    {
        "model": "gpt-4-1106-preview",
        "provider": "openai",
    },
    {
        "model": "gpt-3.5-turbo-1106",
        "provider": "openai",
    },
    {
        "model": "gpt-3.5-turbo",
        "provider": "openai",
    },
    {
        "model": "gpt-3.5-turbo-0301",
        "provider": "openai",
    },
    {
        "model": "gpt-3.5-turbo-0613",
        "provider": "openai",
    },
    {
        "model": "gpt-3.5-turbo-16k",
        "provider": "openai",
    },
    {
        "model": "gpt-3.5-turbo-16k-0613",
        "provider": "openai",
    },
    {
        "model": "gpt-4",
        "provider": "openai",
    },
    {
        "model": "gpt-4-0314",
        "provider": "openai",
    },
    {
        "model": "gpt-4-0613",
        "provider": "openai",
    },
    {
        "model": "gpt-4-32k",
        "provider": "openai",
    },
    {
        "model": "gpt-4-32k-0314",
        "provider": "openai",
    },
    {
        "model": "gpt-4-32k-0613",
        "provider": "openai",
    },
    {
        "model": "gpt-4",
        "provider": "azure",
    },
    {
        "model": "gpt-4-0314",
        "provider": "azure",
    },
    {
        "model": "gpt-4-0613",
        "provider": "azure",
    },
    {
        "model": "gpt-4-32k",
        "provider": "azure",
    },
    {
        "model": "gpt-4-32k-0314",
        "provider": "azure",
    },
    {
        "model": "gpt-4-32k-0613",
        "provider": "azure",
    },
    {
        "model": "gpt-4-1106-preview",
        "provider": "azure",
    },
    {
        "model": "gpt-4-0125-preview",
        "provider": "azure",
    },
    {
        "model": "gpt-3.5-turbo",
        "provider": "azure",
    },
    {
        "model": "gpt-3.5-turbo-0301",
        "provider": "azure",
    },
    {
        "model": "gpt-3.5-turbo-0613",
        "provider": "azure",
    },
    {
        "model": "gpt-3.5-turbo-16k",
        "provider": "azure",
    },
    {
        "model": "gpt-3.5-turbo-16k-0613",
        "provider": "azure",
    },
    {
        "model": "anthropic.claude-3-sonnet-20240229-v1:0",
        "provider": "bedrock",
    },
    {
        "model": "anthropic.claude-3-haiku-20240307-v1:0",
        "provider": "bedrock",
    },
    {
        "model": "anthropic.claude-3-opus-20240229-v1:0",
        "provider": "bedrock",
    },
    {
        "model": "anthropic.claude-v2:1",
        "provider": "bedrock",
    },
    {
        "model": "anthropic.claude-v2",
        "provider": "bedrock",
    },
    {
        "model": "anthropic.claude-instant-v1",
        "provider": "bedrock",
    },
    {
        "model": "meta.llama3-70b-instruct-v1:0",
        "provider": "bedrock",
    },
    {
        "model": "meta.llama3-8b-instruct-v1:0",
        "provider": "bedrock",
    },
    {
        "model": "amazon.titan-text-lite-v1",
        "provider": "bedrock",
    },
    {
        "model": "amazon.titan-text-express-v1",
        "provider": "bedrock",
    },
    {
        "model": "cohere.command-text-v14",
        "provider": "bedrock",
    },
    {
        "model": "ai21.j2-mid-v1",
        "provider": "bedrock",
    },
    {
        "model": "ai21.j2-ultra-v1",
        "provider": "bedrock",
    },
    {
        "model": "meta.llama2-13b-chat-v1",
        "provider": "bedrock",
    },
    {
        "model": "meta.llama2-70b-chat-v1",
        "provider": "bedrock",
    },
    {
        "model": "mistral.mistral-7b-instruct-v0:2",
        "provider": "bedrock",
    },
    {
        "model": "mistral.mixtral-8x7b-instruct-v0:1",
        "provider": "bedrock",
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    meta = MetaData()
    meta.reflect(bind=op.get_bind())
    llm_table = Table("llm", meta)
    op.bulk_insert(llm_table, models)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    meta = MetaData()
    meta.reflect(bind=op.get_bind())
    llm_table = Table("llm", meta)
    d = llm_table.delete().where(llm_table.c.id >= 1)
    op.execute(d)
    # ### end Alembic commands ###
